export const profileData = {
  name: "Pavithra Priyadarshini Selvakumar",
  shortName: "Pavithra Selvakumar",
  headline: "PhD in Environmental Science",
  tagline: "Postdoctoral Research Scientist at Columbia Climate School",
  location: "New York, New York, United States",
  email: "pavithra.s@columbia.edu",
  linkedin: "https://www.linkedin.com/in/pavithra-priyadarshini",
  googleScholar:
    "https://scholar.google.com/citations?user=wn9zdoUAAAAJ&hl=en",
  summary:
    "I get innate joy in learning about the balance between economic, environmental and social needs allowing prosperity for present and future generations. My research focuses on equitable coastal adaptation, AI and climate justice, and institutional sustainability in higher education.",
  experience: [
    {
      id: 1,
      role: "Postdoctoral Research Scientist",
      company: "Columbia Climate School",
      location: "New York City, New York",
      period: "September 2025 - Present",
      highlights: [
        "Leading research within the Resilient Coastal Communities Project in collaboration with the NYC Environmental Justice Alliance and the Center for Sustainable Urban Development.",
        "Principal Investigator of a $49,500 Columbia Climate School seed-funded, community-engaged flood-risk communication pilot in Douala, Cameroon.",
        "Co-Director of the Earth Network on AI, Climate and Society, advancing interdisciplinary research on AI, climate change, sustainability, and society.",
        "Conducting research through the Laboratory for AI, Climate and Society on responsible AI in climate and environmental decision-making, including a systematic review on AI and climate justice.",
        "Teaching Assistant for Ambassador Shefali Razdan Duggal's Politics, Policy & Diplomacy of Climate graduate seminar (Fall 2026).",
        "Co-developing and facilitating courses and workshops, including AI, Climate and Society and AI Foundation 101.",
        "Mentoring undergraduate research on community-centered flood resilience in East Harlem, from thesis development to a policy brief for community organizations.",
      ],
    },
    {
      id: 2,
      role: "Graduate Research Assistant - NSF EPSCoR",
      company: "Oklahoma NSF EPSCoR",
      location: "Oklahoma",
      period: "August 2021 - May 2025",
      highlights: [
        "Worked with Opinion Leader Advisory Network and Extended Peer Scientific Advisory Network for socially sustainable solutions.",
        "Conducted focus group discussions and Group Model Building sessions for complex environmental challenges.",
        "Applied Advocacy Coalition Framework and Narrative Policy Framework for analyzing policy processes.",
        "Facilitated student-peer networking breakout sessions and research retreats.",
      ],
    },
    {
      id: 3,
      role: "Environmental Humanities Research Fellow",
      company: "Oklahoma State University",
      location: "Stillwater, Oklahoma",
      period: "August 2023 - July 2024",
      highlights: [
        'Developed "Moving Orange in a Green Way" for promoting environmentally sustainable practices.',
        'Co-developed "Environmental Thinking and Philosophy" course.',
        "Collaborated on a rideshare application for sustainable campus transit.",
        'Contributed to "Building the Bigger Table" initiative on food security and community bonds.',
      ],
    },
    {
      id: 4,
      role: "Graduate Assistant - Water Quality Testing",
      company: "City of Stillwater (Water Utilities Department)",
      location: "Stillwater, Oklahoma",
      period: "Summer 2023",
      highlights: [
        "Conducted regular monitoring of water quality parameters in the city of Stillwater.",
        "Assessed potential contaminants and ensured the safety and compliance of the water supply.",
        "Implemented a comprehensive water sampling program in coordination with local authorities.",
      ],
    },
    {
      id: 5,
      role: "International Student Ambassador",
      company: "University of East Anglia",
      location: "Norwich, United Kingdom",
      period: "January 2018 - November 2018",
      highlights: [
        "Supported the International Office in administrative activities.",
        "Promoted diversity, equity and inclusion by engaging with future students.",
        "Arranged campus tours for incoming students.",
      ],
    },
    {
      id: 6,
      role: "Project Coordinator - 'Budget Bites' Project",
      company: "Enactus UEA",
      location: "Norwich, United Kingdom",
      period: "September 2017 - September 2018",
      highlights: [
        "Conceptualized and implemented 'Budget Bites', addressing food waste and food poverty in Norwich in partnership with the Norwich Food Hub.",
        "Launched two pop-up stalls, leading to the Budget Bites Café concept for affordable meals and work experience opportunities.",
        "Presented the project at the Enactus UK National Expo in London, aligned with the UN Sustainable Development Goals.",
      ],
    },
    {
      id: 7,
      role: "Engineer (Sustainable Development Team)",
      company: "Tata Consultancy Services",
      location: "Chennai, India",
      period: "June 2015 - August 2017",
      highlights: [
        "Developed user interface to track energy consumption in mobile applications.",
        "Used React.js, JavaScript, Python and CSS for sustainability tools.",
        "Assessed the organization's sustainability performance using statistical skills.",
        "Disseminated awareness about responsible consumption through floor walks.",
      ],
    },
  ],
  education: [
    {
      id: 1,
      degree: "Doctor of Philosophy (PhD)",
      field: "Environmental Science",
      institution: "Oklahoma State University",
      period: "August 2021 - June 2025",
      gpa: "4.0/4.0",
      details:
        "Dissertation: Institutional sustainability in U.S. Land-Grant Universities — A Comparative Study of Oklahoma State University and Colorado State University",
    },
    {
      id: 2,
      degree: "Master of Science",
      field: "Environmental Assessment and Management",
      institution: "University of East Anglia",
      period: "2017 - 2018",
      details:
        "Master's Dissertation: Investigated the role of Corporate Social Responsibility in Hospitals",
    },
    {
      id: 3,
      degree: "Bachelor of Technology (B.Tech.)",
      field: "Information Technology",
      institution: "Anna University (Easwari Engineering College)",
      period: "2011 - 2015",
      details:
        "Completed certification in Human Resource and Business Analytics at LIBA",
    },
  ],
  skills: {
    research: [
      "Qualitative Research",
      "Group Model Building",
      "Semi-structured Interviews",
      "Focus Groups",
      "Policy Analysis",
      "Sustainability Assessment",
      "Stakeholder Engagement",
      "Causal Loop Diagrams",
    ],
    technical: [
      "Python",
      "R Programming",
      "React.js",
      "JavaScript",
      "CSS",
      "LaTeX",
      "ArcGIS",
      "Vensim",
    ],
    tools: [
      "NVivo",
      "IBM SPSS",
      "Stata",
      "Microsoft Office",
      "YOLO Object Detection",
      "Web Scraping",
    ],
    frameworks: [
      "Advocacy Coalition Framework",
      "Narrative Policy Framework",
      "Corporate Social Responsibility",
      "Environmental Justice",
      "Climate Adaptation",
      "AI & Climate Justice",
    ],
    languages: [
      "Tamil (Native)",
      "English (Professional)",
      "Hindi (Basic)",
      "Telugu (Basic)",
      "Malayalam (Basic)",
    ],
  },
  publications: [
    {
      title:
        "How Can AI Address Climate Justice When Women's Voices Are Silenced?",
      authors: "Selvakumar, P. P., Tedesco, M.",
      journal: "State of the Planet (Columbia Climate School)",
      year: 2026,
      url: "https://news.climate.columbia.edu/2026/02/27/how-can-ai-address-climate-justice-when-womens-voices-are-silenced/",
    },
    {
      title: "Parenting a Responsible AI for Climate Governance",
      authors: "Selvakumar, P. P.",
      journal: "State of the Planet (Columbia Climate School)",
      year: 2026,
      url: "https://news.climate.columbia.edu/2026/06/04/raising-ai-for-a-just-climate-future/",
    },
    {
      title:
        "Exploring risk-scapes in Oklahoma: Institutional Trust, Environmental Justice, Climate Change, and Infrastructure",
      authors: "Sibley, M., Peach, K., León-Corwin, M., Selvakumar, P. P., et al.",
      journal: "Safer Communities",
      year: 2024,
    },
    {
      title:
        "Effective Stakeholder Engagement in Environmental Problem-Solving through Group Model Building: An Oklahoma Case Study",
      authors:
        "Olofsson, K. L., Selvakumar, P. P., Peach, K., Leon-Corwin, M., et al.",
      journal: "Environmental Challenges",
      year: 2023,
    },
    {
      title:
        "Investigation of Corporate Social Responsibility in Multi-National Companies to Promote Environmental Sustainability",
      authors: "Selvakumar, P. P.",
      journal: "OIDA International Journal of Sustainable Development",
      year: 2020,
    },
  ],
  awards: [
    "Principal Investigator, Columbia Climate School FY27 Research Seed Fund ($49,500)",
    "Co-Director, Earth Network on AI, Climate and Society ($50,000 project award)",
    "Robberson Summer Dissertation Fellowship 2024 ($8,000)",
    "Humanities Research Group Fellowship 2023-24 ($3,000)",
    "Grand Prize Scientific Poster Presentation ($2,000)",
    "Fae Rawdon Norris Grant, 'Foods of Home - Building a Bigger Table' ($1,980)",
    "International Student Academic Excellence Scholarship - UEA",
    "Top Cultural Ambassador Award 2018 - UEA",
    "Special Initiative Award 2016 - Tata Consultancy Services",
  ],
  totalGrantFunding: "$66,980",
  // Chronological research journey; places and dates verified against the
  // experience and education entries above.
  journey: [
    { place: "Chennai, India", years: "2011 - 2017" },
    { place: "Norwich, UK", years: "2017 - 2018" },
    { place: "Stillwater, Oklahoma", years: "2021 - 2025" },
    { place: "New York City", years: "2025 - Present" },
  ],
};
